SELECT MAX(`SALARY`) FROM hr.employees;

SELECT MAX(`SALARY`) - MIN(`SALARY`) FROM hr.employees;

SELECT `JOB_ID`, AVG(`SALARY`) FROM hr.employees GROUP BY `JOB_ID` ORDER BY AVG(`SALARY`) DESC;

SELECT SUM(`SALARY`) FROM hr.employees;

SELECT ROUND(MIN(`SALARY`),2), ROUND(MAX(`SALARY`),2), ROUND(AVG(`SALARY`),2), ROUND(SUM(`SALARY`),2) FROM hr.employees;

SELECT `JOB_ID`, COUNT(*) FROM hr.employees GROUP BY `JOB_ID` HAVING `JOB_ID` = 'IT_PROG';

SELECT `JOB_ID`, SUM(`SALARY`) FROM hr.employees GROUP BY `JOB_ID`;

SELECT `JOB_ID`, SUM(`SALARY`) AS `total_salary` FROM hr.employees GROUP BY `JOB_ID` HAVING `JOB_ID` = 'IT_PROG' ORDER BY `total_salary` DESC;

SELECT `JOB_ID`, AVG(`SALARY`) FROM hr.employees GROUP BY `JOB_ID` HAVING `JOB_ID` <> 'IT_PROG';

SELECT `DEPARTMENT_ID`, AVG(`SALARY`), COUNT(*) FROM hr.employees GROUP BY `DEPARTMENT_ID` HAVING COUNT(*) > 10;

UPDATE hr.employees
SET `phone_number` = REPLACE(`phone_number`, "515", "777")
WHERE `phone_number` LIKE "515%"

SELECT * FROM hr.employees WHERE CHAR_LENGTH(`FIRST_NAME`) >= 8;

SELECT `EMPLOYEE_ID`, `FIRST_NAME`, YEAR(`HIRE_DATE`) FROM hr.employees;

SELECT `EMPLOYEE_ID`, `FIRST_NAME`, DAY(`HIRE_DATE`) FROM hr.employees;

SELECT `EMPLOYEE_ID`, `FIRST_NAME`, MONTH(`HIRE_DATE`) FROM hr.employees;

SELECT UCASE(`FIRST_NAME`) FROM hr.employees;

SELECT `LAST_NAME`, `HIRE_DATE` FROM hr.employees WHERE `HIRE_DATE` LIKE "1987-07%";

SELECT `FIRST_NAME`, `LAST_NAME`, DATEDIFF(CURRENT_DATE(), `HIRE_DATE`) FROM hr.employees;